const L = require('./lib.js');
const { d, C, W, run, p, bullet, gap, pageBreak, partHead, secHead, subHead,
        note, offenseTable, legend } = L;

const part4 = () => [
  ...partHead('PART IV', 'Schedule of Offenses'),

  p('This Part lists the offenses recognised by TXTAIRE OPC and assigns each to a class. The penalty for each class is set out once, in Section 3.4, and is repeated in the small penalty guide above each table. Before imposing any penalty, read Section 3.5 on mitigating and aggravating circumstances and follow the procedure in Section 3.6.'),
  p('The list is meant to be complete for the ordinary work of the Company. Where an act is genuinely not covered, Section 3.13 applies.'),

  // ---------------------------------------------------------------- 4.1
  secHead('4.1  Offenses Against Attendance and Punctuality'),
  p('Employees are expected to report for work regularly and on time. A leave application shall be filed and approved at least two (2) working days before the expected absence. Where the absence is unforeseen — illness, accident, family emergency, calamity — the employee shall notify the immediate superior as early as possible and not later than two (2) hours after the start of the shift, by any means available, and shall file the leave form on the first day of return.'),
  p('An absence is EXCUSED where notice was given and the reason is legitimate, even if the leave form was filed late. An absence is UNAUTHORIZED where neither notice nor a legitimate reason exists. The distinction matters, and HRD shall not treat an excused absence as an unauthorized one merely because paperwork was late.'),
  legend(),
  offenseTable([
    ['Tardiness — reporting for work after the fifteen (15) minute grace period, four (4) or more times within one (1) calendar month.', 'A', 'Time lost is deducted from pay in the ordinary course. That deduction is not a penalty and does not replace or reduce the disciplinary action.', 'rev'],
    ['Excessive tardiness — accumulated tardiness of three hundred (300) minutes or more within one (1) calendar month.', 'B', null, 'rev'],
    ['Undertime — leaving before the end of the shift without the approval of the immediate superior, two (2) or more times within one (1) calendar month.', 'A'],
    ['Absence for one (1) day where the employee gave timely notice and had a legitimate reason, but failed to file the leave form on the first day of return.', 'A', null, 'new'],
    ['Absence without prior approved leave and without notice (no call, no show) for one (1) working day.', 'B', null, 'rev'],
    ['Absence without approved leave for two (2) to four (4) consecutive working days.', 'C', null, 'rev'],
    ['Absence without approved leave for five (5) or more consecutive working days, or failure to return to work after an approved leave has expired, where the employee cannot be contacted and there is a clear indication of an intention not to return.', 'D', 'Abandonment requires BOTH an unjustified failure to report AND a clear intention to sever the relationship. Before treating an absence as abandonment, HRD shall send the NTE to the employee’s last known address by registered mail or courier and allow the full period to reply. Mere absence, however long, is not abandonment where the employee has explained or has been trying to return.', 'rev'],
    ['Failure to report for a scheduled and previously accepted overtime, emergency call-out or weekend service assignment, without a valid reason and without notice.', 'B', null, 'new'],
    ['Leaving the assigned jobsite, client premises or office during working hours without the permission of the immediate superior.', 'B'],
    ['Failure to report to the assigned client site, or reporting to a site other than the one assigned, without authority.', 'B', null, 'new'],
  ]),
  gap(160),
  note('On the grace period and tardiness', [
    'The grace period is extended from ten (10) to fifteen (15) minutes in recognition of the traffic conditions faced by employees travelling to Laguna, Manila and client sites. The grace period is a concession, not an entitlement to arrive late every day; the tardiness count is reckoned from the official start of the shift, not from the end of the grace period.',
    'The previous edition defined excessive tardiness at 260 minutes in a month and made tardiness in excess of four times in one month punishable without stating the penalty. This edition states both the threshold and the class.',
  ]),

  // ---------------------------------------------------------------- 4.2
  secHead('4.2  Offenses on Timekeeping and Records'),
  p('Accurate time and service records are the basis of every employee’s pay and of every client’s bill. A genuine mistake in a time record is a clerical matter. Deliberately falsifying one is fraud.'),
  legend(),
  offenseTable([
    ['Unintentional failure to log in or log out on the biometric device or timesheet, three (3) or more times within one (1) calendar month.', 'A', 'The hours actually worked shall be paid in full on the basis of a Time Correction Form certified by the immediate superior. No deduction shall be made, and the employee shall not be marked absent, for hours actually worked. See Section 3.12.', 'rev'],
    ['Repeated failure or refusal to log in or log out after having been issued a written warning for the same conduct.', 'B'],
    ['Failure to submit a required timesheet, service report, job order or accomplishment report within the prescribed period.', 'A', null, 'new'],
    ['Giving a false reason to justify an absence, tardiness or undertime.', 'C', null, 'rev'],
    ['Logging in or logging out on behalf of another employee, or allowing or asking another employee to do so on one’s behalf.', 'D', 'Both employees are liable. Where the arrangement was a single, isolated act with no gain obtained and full disclosure was made before discovery, the Panel may consider mitigation under Section 3.5.', 'rev'],
    ['Falsifying, altering or tampering with a time record, timesheet, daily time record, service report, job order, gate pass, delivery receipt or any other company or client record.', 'D'],
    ['Knowingly receiving salary, overtime pay, allowance, reimbursement or any benefit to which one is not entitled by reason of a falsified or erroneous record, and failing to report it within a reasonable time.', 'D', 'An employee who promptly reports an overpayment and returns it is not liable under this item.'],
    ['Refusing to submit to, or tampering with, the Company’s timekeeping system, including the biometric device.', 'C', null, 'new'],
  ]),

  // ---------------------------------------------------------------- 4.3
  secHead('4.3  Offenses Against Health, Safety and Security'),
  p('The Company’s work involves electricity, pressurised refrigerant, rotating machinery and elevated platforms, so safety rules here are not paperwork. Under Republic Act No. 11058 and Department Order No. 198-18 every worker may refuse unsafe work, and no employee shall be penalised for exercising that right in good faith.'),
  legend(),
  offenseTable([
    ['Failure to observe housekeeping and orderliness in the office, stockroom, service vehicle or jobsite; leaving tools, materials or refuse uncleared.', 'A'],
    ['Smoking or vaping outside a designated smoking area, or within client premises where it is prohibited.', 'A', null, 'new'],
    ['Failure or refusal to comply with a lawful health or medical requirement of the Company, such as the annual physical examination or a fit-to-work clearance.', 'A'],
    ['Failure to wear or properly use the prescribed personal protective equipment (helmet, safety shoes, gloves, eye protection, harness, insulated tools) while on duty.', 'B', null, 'new'],
    ['Failure to immediately report to the immediate superior or the Safety Officer a work-related accident, injury, near-miss, spill, or an unsafe or unhealthy condition.', 'B', 'A severe penalty discourages the very reporting this rule exists to produce. Prompt, good-faith reporting of an incident in which the employee was at fault is treated as mitigating.', 'rev'],
    ['Lending one’s company identification card, access card, gate pass or uniform to another person; or using that of another.', 'B', null, 'rev'],
    ['Deliberately concealing a known communicable disease, or a medical condition that renders the employee unfit for the work assigned, where concealment places the employee or others at risk.', 'C', 'Does not apply to HIV, Hepatitis B or tuberculosis status, which need never be disclosed and can never ground discipline. See Section 5.10.', 'rev'],
    ['Forcing entry into the office, stockroom, tool crib or client premises outside authorized hours; or opening another person’s locker, drawer, bag or workstation without authority.', 'C', null, 'rev'],
    ['Willful refusal to follow a safety instruction, or willful violation of a safety rule, which exposes the employee or any other person to the danger of death or serious injury — such as working at height without fall protection, working on energised equipment without lock-out / tag-out, defeating a machine guard or interlock, or operating equipment one is not certified to operate.', 'D', 'Where the violation was inadvertent rather than willful and no injury resulted, the offense is the failure to wear or properly use personal protective equipment, above, and not this one.', 'rev'],
    ['Unauthorized possession or carrying of a firearm, explosive, or other deadly weapon within company or client premises, or in a company vehicle.', 'D'],
    ['Use, possession, sale, distribution, or being under the influence of dangerous drugs within company or client premises, in a company vehicle, or while on duty.', 'D', 'Subject to the procedure and safeguards in Section 5.8, which provides for referral and treatment in appropriate cases.', 'rev'],
    ['Reporting for work under the influence of alcohol; or drinking alcoholic beverages within company or client premises or during working hours.', 'C', 'Class D where the employee is assigned to driving, work at height, or work on energised equipment.', 'rev'],
    ['Final conviction by a court of a crime involving moral turpitude, or of any crime against the Company, its officers, employees, clients or their property.', 'D', 'A pending charge is not a conviction. Where the act is independently an offense under this Code, the Company may proceed on that basis.', 'rev'],
  ]),

  // ---------------------------------------------------------------- 4.4
  secHead('4.4  Offenses Related to Job Performance'),
  p('Poor performance and misconduct are different things. Genuine inability to meet a standard is addressed through coaching, training and a written performance improvement plan under Section 6.2, not through this Part. This Section deals with conduct: not doing the work one is capable of doing, doing it carelessly, or refusing to do it.'),
  legend(),
  offenseTable([
    ['Wasting time, loafing, idling, or engaging in personal activities during working hours.', 'A'],
    ['Failure to wear the prescribed uniform, or to maintain the prescribed grooming and appearance, while on duty, except when excused.', 'A'],
    ['Failure to keep the company-issued mobile phone or radio charged, available and reachable during working hours or while on call.', 'A', 'No fine shall be imposed and no unit shall be confiscated for this offense. See Section 3.12.', 'rev'],
    ['Sleeping during working hours, or deliberately evading assigned work.', 'B', 'Where the employee is driving, working at height, or monitoring energised or pressurised equipment, this is treated as Class C.', 'rev'],
    ['Simple negligence or inefficiency in the performance of duties resulting in no loss, or in a loss of not more than Five Thousand Pesos (P5,000.00).', 'B', 'The previous edition set this threshold at Two Hundred Pesos (P200.00), which is no longer a meaningful amount.', 'rev'],
    ['Negligence in the performance of duties resulting in a loss of more than Five Thousand Pesos (P5,000.00) but not more than Thirty Thousand Pesos (P30,000.00).', 'C', null, 'rev'],
    ['Gross and habitual neglect of duties; or negligence resulting in a loss of more than Thirty Thousand Pesos (P30,000.00); or negligence resulting in serious physical injury to any person.', 'D', 'Under Article 297(b) of the Labor Code, neglect must be both GROSS and HABITUAL to justify dismissal. A single act of negligence, however costly, will ordinarily be dealt with under the negligence tiers above unless it was so reckless as to amount to serious misconduct.', 'rev'],
    ['Willful disobedience of, or refusal to carry out, a lawful and reasonable instruction of a superior in connection with the employee’s work.', 'C', 'Three things must be shown: the order was lawful and reasonable, it was made known to the employee, and it related to the duties the employee was engaged to perform. Refusing an unlawful order, or refusing work that is imminently dangerous, is not disobedience.', 'rev'],
    ['Willful holding back, slowing down or limiting work output; or inducing or encouraging a fellow employee to do so.', 'C', 'This does not apply to lawful concerted activity, which is a protected right.'],
    ['Acting as a broker or agent for, or negotiating on behalf of, a client, unit owner, supplier or third person in a transaction involving the Company, without written authority.', 'C', null, 'rev'],
    ['Accepting or soliciting, directly or indirectly, any sum of money, commission, discount, gift or benefit from a supplier, contractor, client or applicant in consideration of any act pertaining to one’s work.', 'D'],
    ['Disclosing to an unauthorized person, or using for personal benefit, trade secrets, costing, pricing, bid information, client lists, technical drawings, or other confidential information of the Company or of its clients.', 'D'],
    ['Sabotage, or any deliberate act intended to disrupt operations or to damage the Company, its property, its clients, or the property of its clients, whether or not damage actually resulted.', 'D'],
  ]),

  // ---------------------------------------------------------------- 4.5
  secHead('4.5  Offenses Against Company and Client Property'),
  p('Penalties under this Section are without prejudice to restitution, which is governed by Section 3.12. The value of loss or damage means the actual, documented cost of repair or replacement, not a list price or an estimate made without inspection. Where the value is disputed, the burden of proving it rests on the Company.'),
  legend(),
  offenseTable([
    ['Careless, improper or unauthorized use of company or client property, tools, materials, equipment, refrigerant or supplies, resulting in no loss or in a loss of not more than Five Thousand Pesos (P5,000.00).', 'B', null, 'rev'],
    ['Careless, improper or unauthorized use of company or client property, tools, materials, equipment, refrigerant or supplies, resulting in a loss of more than Five Thousand Pesos (P5,000.00) but not more than Thirty Thousand Pesos (P30,000.00).', 'C'],
    ['Careless, improper or unauthorized use of company or client property, tools, materials, equipment, refrigerant or supplies, resulting in a loss of more than Thirty Thousand Pesos (P30,000.00).', 'D'],
    ['Failure to report the loss, damage or malfunction of company or client property, tools or equipment in one’s custody.', 'B', null, 'new'],
    ['Any act of vandalism that defaces or damages company or client property, or the property of another person within company or client premises.', 'C', null, 'rev'],
    ['Willful or malicious damage to, or destruction of, any property or equipment owned by the Company or by its clients.', 'D'],
    ['Unauthorized use of a company or client vehicle, without resulting damage or injury.', 'C'],
    ['Unauthorized use of a company or client vehicle, resulting in damage or injury.', 'D'],
    ['Driving a company vehicle in a reckless or imprudent manner, or while not holding the appropriate valid licence, without resulting damage or injury.', 'C'],
    ['Driving a company vehicle in a reckless or imprudent manner, or while not holding the appropriate valid licence, resulting in damage to property or injury to any person.', 'D'],
    ['Attempted or frustrated removal of company or client property from the premises without proper authorization or gate pass, where the property was recovered and no loss resulted.', 'C', null, 'rev'],
    ['Removing company or client property from the premises without authorization, where the property was taken away or lost.', 'D'],
    ['Theft or pilferage of property or money belonging to the Company, a client, a co-employee, or any third person, within company or client premises; including obtaining property or money under fraudulent or false pretences.', 'D'],
  ]),

  // ---------------------------------------------------------------- 4.6
  secHead('4.6  Offenses Against Honesty and Integrity'),
  p('The Company entrusts employees with money, materials, client records and its own good name. Dishonesty destroys the trust on which employment rests, and the offenses in this Section are therefore classified as serious. That classification is not mechanical: see the note at the end of this Section.'),
  legend(),
  offenseTable([
    ['Misappropriation, embezzlement or malversation of company or client funds or property.', 'D', 'Malversation means the unauthorized taking of company funds or property, or any wrongdoing in relation to them.'],
    ['Using company or client funds, property or facilities for personal purposes without the prior approval of the immediate superior or other accountable person.', 'D'],
    ['Creating fictitious or "ghost" transactions; or falsifying company or client records, receipts, invoices, quotations, job orders, liquidations or documents.', 'D'],
    ['Withholding funds due to the Company or to a client; kiting; short remittance or non-remittance of collections.', 'D'],
    ['Non-issuance or wrongful issuance of official receipts, invoices or commercial documents where these are required.', 'D'],
    ['Forgery, or the misuse or abuse of company funds.', 'D'],
    ['Engaging privately, directly or through another person, in a business that competes with the Company; or diverting to oneself or to another a business opportunity belonging to the Company or to a client.', 'D'],
    ['Undeclared outside employment, consultancy or sideline that conflicts with the employee’s duties, or that makes use of company time, tools, materials, vehicles or information.', 'C', 'Outside work that does not conflict and does not use company resources is not an offense, but must be declared under Section 2.3.', 'new'],
    ['Failure to declare a conflict of interest required to be declared under Section 2.3.', 'C', null, 'new'],
    ['Making a false statement, or submitting a falsified or fraudulently obtained document, in an application for employment, promotion, transfer, leave, reimbursement, loan or any benefit.', 'D', null, 'new'],
    ['Conspiring or conniving with, directing, inducing or instigating another person to commit any of the foregoing.', 'D'],
  ]),
  gap(160),
  note('Proportionality in dishonesty cases', [
    'Dishonesty is presumed grave, and dismissal is the normal penalty. But the Supreme Court has repeatedly set aside dismissals where the amount involved was trivial, the employee had long unblemished service, and there was no real bad faith. HRD and the Panel shall therefore consider, and record in the Case Evaluation Form: the amount or value involved; whether the employee holds a position of trust; whether there was concealment; whether restitution was made voluntarily and before discovery; and the length and quality of the employee’s service.',
    'Where the Panel concludes that a penalty lower than dismissal is warranted, it shall say so in writing with its reasons, and the decision rests with the Owner or General Manager. This is the exception and must be justified — but it must remain available, or the Code becomes the very thing this edition was issued to correct.',
  ], { edge: C.blue, fill: 'EEF3FB', labelColor: C.navy }),

  // ---------------------------------------------------------------- 4.7
  secHead('4.7  Offenses Against Proper Conduct and Behavior'),
  p('Employees work in close quarters, in clients’ buildings, often under time pressure. The standard expected is ordinary professional courtesy. This Section is not intended to police personality, ordinary disagreement, or lawful complaint about working conditions.'),
  legend(),
  offenseTable([
    ['Horseplay or unruly conduct which causes or tends to cause disorder, disrupts work, or creates a disturbance within company or client premises, where no loss, damage or injury results.', 'A'],
    ['Horseplay or unruly conduct which causes or tends to cause disorder, disrupts work, or creates a disturbance within company or client premises, where loss or damage to property, or injury to any person, results.', 'C'],
    ['Removing, defacing or tampering with a notice posted on the company bulletin board or issued through official company channels.', 'A'],
    ['Discourtesy, rudeness or improper behaviour towards a client, a client’s visitor or tenant, a supplier, or a member of the public.', 'B', null, 'rev'],
    ['Gross or repeated discourtesy towards a client, resulting in the loss of, or serious damage to, a client account or to the Company’s reputation.', 'D', null, 'rev'],
    ['Acts of disrespect towards a superior, co-employee or third person; the use of foul, abusive or insulting language or gestures; or challenging another to a fight, in the course of business.', 'B'],
    ['Spreading malicious rumours, or creating intrigues against a co-employee or officer, which tend to cast dishonour, discredit or contempt upon that person.', 'B', 'The previous edition penalised this with a fifteen-day suspension on the first offense and dismissal on the second. That is out of proportion to the conduct in the ordinary case.', 'rev'],
    ['Making a threat of harm against a superior, co-employee, client or third person.', 'C', null, 'new'],
    ['Making such a threat while carrying or brandishing a weapon, or in a manner that places the person threatened in immediate fear of serious harm.', 'D', null, 'new'],
    ['Bullying — repeated verbal, psychological, social or online conduct directed at a co-employee that creates an intimidating, hostile, humiliating or offensive work environment.', 'C', 'A single serious incident may be treated as bullying where its effect is equivalent. Legitimate performance management, correction and discipline are not bullying.', 'new'],
    ['Fighting, or provoking or instigating a fight, within company or client premises or while on duty, where no serious physical injury results and no weapon is used.', 'C', 'The previous edition imposed dismissal on the first offense. Under this edition dismissal is reserved for the aggravated forms in items 12 and 13. Where an employee was genuinely defending themselves, no penalty shall be imposed.', 'rev'],
    ['Fighting where serious physical injury results, where a weapon is used, or where the employee was the instigator or aggressor.', 'D', null, 'rev'],
    ['Willfully or deliberately inflicting physical injury upon a superior, co-employee, client or third person, in connection with work, whether within or outside company premises.', 'D', 'Where the injury is minor, the incident was isolated, and there was substantial provocation, the Panel may consider mitigation under Section 3.5.', 'rev'],
    ['Sexual harassment, or gender-based sexual harassment, in any of the forms defined in Republic Act No. 7877 and Republic Act No. 11313, whether committed in person, in writing, or through any online or electronic medium.', 'D', 'Complaints are handled by the Committee on Decorum and Investigation under Section 5.9, which takes precedence over Part III. Where the act falls under the "light" or "less grave" categories of RA 11313 (such as catcalling, wolf-whistling or persistent unwanted comments), the graduated penalties in that law and in Section 5.9 apply instead, beginning at Class B.', 'rev'],
    ['Immoral or indecent conduct, or engaging in sexual activity, within company or client premises.', 'D'],
    ['Gambling, or soliciting or accepting bets, or lending money to be used for such activity, within company or client premises or during working hours.', 'B', 'The previous edition imposed dismissal on the first offense.', 'rev'],
    ['Engaging in any private business, or selling goods or services, within company or client premises or during working hours.', 'B'],
    ['Borrowing money, merchandise or goods from a client, a client’s staff, tenant or visitor, or from a supplier or contractor of the Company.', 'C', null, 'rev'],
    ['Soliciting or borrowing money, merchandise or goods from a subordinate; or lending money to a subordinate at interest.', 'C', 'The previous edition imposed dismissal on the first offense. This edition treats it as grave but correctable, unless coercion or abuse of authority is shown, in which case Section 4.8 applies.', 'rev'],
    ['Posting, publishing, sharing or distributing, in any medium including social media, obscene, defamatory or malicious material, or confidential company or client information, which damages or tends to damage the reputation of the Company, its officers, its employees or its clients.', 'C', 'Where the posting discloses confidential or client data, identifies a client, or is done maliciously and causes serious damage, this is treated as Class D. Lawful comment on working conditions, and lawful concerted activity, are protected and are not offenses. Acts falling under the Cybercrime Prevention Act may additionally be referred for prosecution.', 'rev'],
    ['Planting or fabricating evidence against a superior or a co-employee; or knowingly filing a false complaint or giving false testimony in a company investigation.', 'D'],
    ['Refusing without valid reason to cooperate in an official company investigation, or obstructing one, including by destroying evidence or influencing a witness.', 'C', 'An employee who is themselves the respondent in the investigation has the right to remain silent and to decline to answer, and shall not be penalised under this item for exercising that right.', 'new'],
    ['Retaliating against any person who, in good faith, reported a violation, filed a complaint, gave evidence, or took part in an investigation.', 'D', null, 'new'],
  ]),

  // ---------------------------------------------------------------- 4.8
  secHead('4.8  Accountability of Supervisors and Managers'),
  p('Supervisors and managers hold positions of trust. They are held to the same standards as everyone else, and to these additional ones. A supervisor who commits an offense listed in Sections 4.1 to 4.7 is subject to the same class, with their position treated as an aggravating circumstance under Section 3.5.'),
  legend(),
  offenseTable([
    ['Failure to disseminate to subordinates this Code, company policies, work rules, safety procedures and other work-related matters.', 'B'],
    ['Failure to report to HRD, within five (5) working days of learning of it, a violation of this Code committed by a subordinate.', 'B'],
    ['Failure to conduct, document or discuss the required performance evaluations of subordinates.', 'A', null, 'new'],
    ['Failure to properly supervise, resulting in a substantial loss to the Company or a client, or in an injury that could reasonably have been prevented.', 'C', null, 'new'],
    ['Showing manifest partiality or favouritism in work assignments, overtime allocation, evaluation, recommendation for promotion, or discipline.', 'C', null, 'new'],
    ['Imposing on a subordinate any disciplinary penalty, fine, wage deduction or informal sanction outside the procedure laid down in Part III of this Code.', 'C', null, 'new'],
    ['Using preventive suspension as an informal penalty, or to avoid holding a hearing.', 'C', null, 'new'],
    ['Directing, instructing or requiring a subordinate to commit an act that violates this Code, a company policy, or the law; or to falsify a record.', 'D', null, 'new'],
    ['Failing to act upon, or concealing, a report of sexual harassment, gender-based harassment, bullying, discrimination, or a serious unsafe condition.', 'D', null, 'new'],
    ['Retaliating against, or permitting or directing retaliation against, an employee who in good faith reported a violation, filed a complaint, or participated in an investigation.', 'D', null, 'new'],
    ['Soliciting money, goods, services or personal favours from a subordinate as a condition, express or implied, of favourable treatment.', 'D', null, 'new'],
  ]),
  gap(160),
  note('For supervisors: the three things that most often go wrong', [
    'First, informal punishment. Sending someone home for the day, cutting their overtime, or moving them to a worse assignment because of something they did is a penalty imposed without due process. Report it to HRD and let the process run.',
    'Second, delay. The sixty-day prescriptive period in Section 3.11 runs from the moment YOU knew. Sitting on a report can extinguish the Company’s right to act on it.',
    'Third, the vague notice. "You have been remiss in your duties" is not a Notice to Explain. State the act, the date, the place, and the provision violated, or the whole case fails on procedure no matter how right you were on the facts.',
  ], { edge: C.blue, fill: 'EEF3FB', labelColor: C.navy }),
];

module.exports = { part4 };
