# -*- coding: utf-8 -*-
"""Content for the HR framework images. Aligned with Philippine labor law."""

FRAMEWORKS = [
 {
  "file": "01-mandatory-benefits",
  "title": "MANDATORY BENEFITS",
  "basis": "LEGAL BASIS: Labor Code of the Philippines (Arts. 86, 87, 94, 95, 100) | RA 11199 SSS | RA 11223 PhilHealth | RA 9679 Pag-IBIG | PD 851 13th Month Pay | PD 626 Employees Compensation | RA 7641 Retirement Pay | RA 11210, RA 8187, RA 11861, RA 9710, RA 9262 Leave Laws",
  "what": "Benefits every employer must give by law, no matter what company policy says. They cannot be waived, reduced or traded off. Unremitted contributions carry penalties, interest and personal liability for the responsible officers, while withdrawing a benefit already granted violates the non-diminution rule.",
  "phases": [
    {"name": "REGISTER &\nENROLL",
     "body": ["Register the company with SSS, PhilHealth, Pag-IBIG and BIR as an employer.",
              "Enroll every new hire within the first month of employment.",
              "Collect SSS, PhilHealth, Pag-IBIG and TIN numbers; assist those without one.",
              "Report new hires and separations using the required employer forms."],
     "out": "Employer registration numbers; complete government IDs in each 201 file; filed new-hire reports."},
    {"name": "COMPUTE\nPER PAYROLL",
     "body": ["Apply the current contribution tables every cutoff.",
              "SSS, PhilHealth and Pag-IBIG each have an employer share and an employee share.",
              "Deduct the employee share only; the employer share is never charged to the worker.",
              "Show every deduction on the payslip."],
     "out": "Payroll register with contribution breakdown; payslip showing each mandatory deduction."},
    {"name": "REMIT &\nREPORT",
     "body": ["Generate the Payment Reference Number and pay on or before the deadline.",
              "File the monthly and quarterly contribution and loan reports.",
              "Withhold and remit income tax; issue BIR Form 2316.",
              "Keep proof of payment on file for at least three (3) years."],
     "out": "Validated payment confirmations; filed contribution and loan collection lists; BIR 2316 per employee."},
    {"name": "GRANT LEAVES\n& PAY BENEFITS",
     "body": ["5-day Service Incentive Leave after one year of service.",
              "105-day maternity, 7-day paternity, 7-day solo parent, 10-day VAWC, 2-month special leave for women.",
              "Holiday pay, premium pay, overtime and night shift differential.",
              "13th month pay on or before 24 December."],
     "out": "Approved leave records with supporting documents; 13th month payout register; DOLE 13th month report."},
    {"name": "ASSIST CLAIMS\n& SELF-AUDIT",
     "body": ["Help employees file sickness, maternity, EC, disability and loan claims.",
              "Reconcile posted contributions against payroll every quarter.",
              "Fix gaps, delinquencies and unposted months at once.",
              "Self-audit yearly against the DOLE compliance checklist."],
     "out": "Filed claims and reimbursements; quarterly reconciliation; annual compliance audit report; DOLE-ready file."},
  ],
  "note": "REMINDER: Contribution rates, salary brackets and ceilings change by circular. Confirm the current SSS, PhilHealth and Pag-IBIG schedules and the BIR withholding table before every payroll run.",
 },
 {
  "file": "02-code-of-discipline",
  "title": "CODE OF DISCIPLINE",
  "basis": "LEGAL BASIS: Labor Code Arts. 297-299 [282-284] Just and Authorized Causes | DOLE Department Order No. 147-15 | Omnibus Rules Implementing the Labor Code, Book V Rule XXIII (preventive suspension) | RA 7877 Anti-Sexual Harassment | RA 11313 Safe Spaces Act",
  "what": "A published table of offenses and penalties, plus the procedure for enforcing it. A rule can only be enforced if it is reasonable, made known to the employee beforehand and applied consistently. A valid cause is not enough on its own; procedural due process must also be observed.",
  "phases": [
    {"name": "DRAFT &\nCLASSIFY",
     "body": ["List offenses by gravity: Minor, Serious, Grave.",
              "Set graduated penalties: verbal warning, written warning, suspension, dismissal.",
              "Anchor grave offenses on the just causes under Art. 297.",
              "Keep every penalty proportionate to the offense."],
     "out": "Approved Code of Discipline matrix with offense classes, penalties and repetition levels."},
    {"name": "PUBLISH &\nACKNOWLEDGE",
     "body": ["Orient all employees, including new hires on day one.",
              "Post it on the employee portal and the bulletin board.",
              "Secure a signed acknowledgment from every employee.",
              "File the acknowledgment in the 201 file."],
     "out": "Signed acknowledgment receipts; orientation attendance sheets; posted and accessible copy."},
    {"name": "REPORT &\nINVESTIGATE",
     "body": ["Receive the incident report in writing.",
              "Gather evidence, records and witness statements.",
              "Use preventive suspension only if the employee poses a real threat, for a maximum of 30 days.",
              "Keep the matter confidential."],
     "out": "Incident report; evidence file; investigation findings; preventive suspension memo when justified."},
    {"name": "TWIN-NOTICE\nDUE PROCESS",
     "body": ["First Notice to Explain: state the specific acts, the rule violated and the possible penalty.",
              "Give at least five (5) calendar days to submit a written explanation.",
              "Conduct an administrative hearing or conference.",
              "Weigh the defenses on the evidence, not on assumption."],
     "out": "Notice to Explain with proof of receipt; written explanation; hearing minutes and attendance."},
    {"name": "DECIDE &\nMONITOR",
     "body": ["Issue the second notice, the Decision, stating the facts and the grounds relied upon.",
              "Apply exactly the penalty in the matrix; treat like cases alike.",
              "Serve the decision and file it in the 201 file.",
              "Track repeat offenses within the prescribed period."],
     "out": "Notice of Decision; served penalty; disciplinary log; clean-record reset after the prescribed period."},
  ],
  "note": "REMINDER: Dismissal without the twin-notice procedure exposes the company to damages even when the cause is valid. Document the service and receipt of every notice.",
 },
 {
  "file": "03-hiring-process",
  "title": "HIRING PROCESS",
  "basis": "LEGAL BASIS: Labor Code Art. 296 [281] Probationary Employment | RA 10911 Anti-Age Discrimination | RA 11261 First Time Jobseekers Assistance | RA 10173 Data Privacy Act | RA 7277 Magna Carta for Persons with Disability | RA 9710 Magna Carta of Women | RA 11166 (no HIV testing as a hiring condition) | RA 11058 OSH",
  "what": "End-to-end recruitment that is fair, non-discriminatory and privacy-compliant, ending in a valid written contract with the standards communicated at the time of engagement. Selection must rest on job-related qualifications only, never on age, sex, civil status, pregnancy, religion, disability or health status.",
  "phases": [
    {"name": "REQUISITION\n& JOB POST",
     "body": ["Approved manpower request with a budgeted position.",
              "Job description limited to bona fide occupational qualifications.",
              "No age, sex, civil status, religion or health-status limits in the ad.",
              "State the pay range, schedule and work location honestly."],
     "out": "Approved manpower requisition form; compliant, non-discriminatory job posting."},
    {"name": "SOURCE\n& SCREEN",
     "body": ["Post through PESO, job portals, schools and referrals.",
              "Screen strictly against the stated criteria.",
              "Put a privacy notice and consent clause on the application form.",
              "Store applicant data securely and set a disposal date."],
     "out": "Screened shortlist with reasons; signed data privacy consent; secured applicant database."},
    {"name": "INTERVIEW\n& ASSESS",
     "body": ["Use a structured guide with the same core questions for everyone.",
              "Give job-related skills or behavioral tests.",
              "Score on a common sheet and write the reason for each rating.",
              "Verify references and credentials with consent."],
     "out": "Interview evaluation sheets; test results; documented selection justification."},
    {"name": "OFFER &\nREQUIREMENTS",
     "body": ["Issue a written job offer: pay, benefits, schedule, status, reporting date.",
              "Require only job-related pre-employment medical exams.",
              "First-time jobseekers are exempt from fees for the government documents covered by RA 11261.",
              "Collect SSS, PhilHealth, Pag-IBIG, TIN and NBI documents."],
     "out": "Signed and accepted job offer; complete pre-employment requirements; fit-to-work clearance."},
    {"name": "CONTRACT\n& ONBOARD",
     "body": ["Sign the employment contract before the first day of work.",
              "Probation must not exceed six (6) months, with regularization standards given in writing at engagement.",
              "Enroll with SSS, PhilHealth, Pag-IBIG and BIR.",
              "Orient on the Code of Discipline, safety and company policies."],
     "out": "Signed contract and standards form; complete 201 file; government enrollment; onboarding checklist."},
  ],
  "note": "REMINDER: If the regularization standards are not made known at the time of engagement, the employee is deemed regular from day one. Keep the signed standards form in the 201 file.",
 },
 {
  "file": "04-employee-retention",
  "title": "EMPLOYEE RETENTION",
  "basis": "LEGAL BASIS: Labor Code (wages, hours of work, rest days, security of tenure, Art. 100 non-diminution) | RA 11036 Mental Health Act & DOLE D.O. 208-20 | RA 11058 & D.O. 198-18 Occupational Safety and Health | RA 11165 Telecommuting Act | D.O. 53-03 Drug-Free Workplace | D.O. 102-10 HIV/AIDS | D.O. 73-05 Tuberculosis | RA 11313 Safe Spaces Act",
  "what": "A managed program to keep capable employees: correct pay, a safe and respectful workplace, growth, a real voice and wellbeing support. Retention is measured with data - turnover, tenure and exit reasons - not with impressions. Most avoidable resignations trace back to a compliance or supervision failure, not to salary alone.",
  "phases": [
    {"name": "MEASURE\nTHE BASELINE",
     "body": ["Track turnover rate, average tenure, absenteeism and exit reasons monthly.",
              "Segment by department, position and tenure band.",
              "Identify where and when people actually leave.",
              "Set a target turnover rate for the year."],
     "out": "Turnover dashboard; exit interview summary; identified high-attrition units."},
    {"name": "LISTEN &\nDIAGNOSE",
     "body": ["Run an engagement or pulse survey with anonymous responses.",
              "Hold stay interviews with high performers before they resign.",
              "Operate the grievance machinery and labor-management committee.",
              "Trace every recurring complaint to a root cause and an owner."],
     "out": "Engagement report; issue log with assigned owners and deadlines."},
    {"name": "FIX THE\nLEGAL BASICS",
     "body": ["Pay on time and in full, with correct overtime, premium and night differential.",
              "Complete benefits and posted government contributions.",
              "Safety officer, health committee and OSH program in place.",
              "Enforce anti-harassment and mental health policies."],
     "out": "Corrected payroll and benefits; posted OSH and Safe Spaces policies; closed compliance gaps."},
    {"name": "GROW &\nREWARD",
     "body": ["Career path, training calendar and internal hiring first.",
              "Merit increases, incentives and recognition tied to appraisal results.",
              "Company leaves and wellness programs beyond the legal minimum.",
              "Flexible or telecommuting arrangements in writing, with equal treatment."],
     "out": "Training records; promotion and recognition register; signed telecommuting agreements."},
    {"name": "REVIEW &\nADJUST",
     "body": ["Review retention KPIs against target every quarter.",
              "Report results and the cost of turnover to management.",
              "Retire what did not work; scale what did.",
              "Update the plan and repeat the cycle."],
     "out": "Quarterly retention report; cost-of-turnover analysis; approved action plan for the next quarter."},
  ],
  "note": "REMINDER: Retention perks are voluntary, but a benefit given regularly and deliberately can ripen into company practice that cannot be unilaterally withdrawn (non-diminution rule, Art. 100).",
 },
 {
  "file": "05-performance-improvement-plan",
  "title": "PERFORMANCE IMPROVEMENT PLAN",
  "basis": "LEGAL BASIS: Labor Code Art. 296 [281] Probationary Standards | Art. 297 [282] (b) Gross and Habitual Neglect of Duties | DOLE Department Order No. 147-15 | Settled jurisprudence on communicated standards, coaching and due process",
  "what": "A time-bound, documented coaching program for an employee performing below standard. It is a corrective tool first, and most plans should end in recovery. It is also the evidence trail that makes any later separation defensible, because poor performance must be proven with records, not with opinion.",
  "phases": [
    {"name": "IDENTIFY\nTHE GAP",
     "body": ["Compare actual output against the standards given in writing.",
              "Gather hard data: KPIs, error rates, missed deadlines, complaints.",
              "Rule out causes outside the employee: tools, training, workload, supervision.",
              "Confirm the standard was actually communicated."],
     "out": "Performance gap analysis supported by records; confirmed copy of the communicated standards."},
    {"name": "DESIGN\nTHE PLAN",
     "body": ["State the specific gap and the measurable target.",
              "Define the support: coaching, training, mentoring, tools.",
              "Set the duration, normally 30 to 90 days, and the review dates.",
              "State the consequence plainly and fairly."],
     "out": "Written PIP document with targets, support, timeline, review schedule and stated consequence."},
    {"name": "LAUNCH\nMEETING",
     "body": ["Discuss it in person; never spring it as a surprise.",
              "Let the employee explain their side and propose adjustments.",
              "Both parties sign; if the employee refuses, note it with a witness.",
              "Give the employee a copy on the spot."],
     "out": "Signed PIP; meeting minutes; witnessed refusal note when applicable; copy furnished to the employee."},
    {"name": "COACH\n& MONITOR",
     "body": ["Hold weekly or bi-weekly check-ins with written notes.",
              "Actually deliver the training and resources promised.",
              "Record progress and misses as they happen, not at the end.",
              "Escalate blockers that management must resolve."],
     "out": "Dated coaching logs; progress records against each target; evidence of training delivered."},
    {"name": "CLOSE\n& DECIDE",
     "body": ["Passed: close in writing and monitor for three months.",
              "Partial: extend once, with a revised target.",
              "Failed: proceed to twin-notice due process before any separation.",
              "File everything in the 201 file."],
     "out": "PIP closure report; sustained-performance review; Notice to Explain if warranted; 201 filing."},
  ],
  "note": "REMINDER: A PIP does not replace due process. Separation for poor performance still requires a Notice to Explain, an opportunity to be heard, and a written Decision citing the facts and grounds.",
 },
 {
  "file": "06-employee-portal",
  "title": "EMPLOYEE PORTAL",
  "basis": "LEGAL BASIS: RA 10173 Data Privacy Act & NPC Circular 16-01 (security of personal data) | RA 8792 E-Commerce Act (validity of electronic documents) | Labor Code Book III Rule X (payslips; records kept for three years) | BIR regulations on electronic payslips and Form 2316",
  "what": "One secure self-service system where employees view payslips, file leaves, read announcements and update their information. It cuts paper and repetitive HR queries, but it holds sensitive personal data, so privacy, access control and an audit trail are part of the build, not an afterthought.",
  "phases": [
    {"name": "SCOPE\n& POLICY",
     "body": ["Define the modules: payslip, leave, 201 file, announcements, requests.",
              "Set user roles and access levels: employee, supervisor, HR, admin.",
              "Approve the privacy notice and acceptable-use policy.",
              "Decide what data the portal will and will not hold."],
     "out": "Approved portal scope; user access matrix; privacy notice; acceptable-use policy."},
    {"name": "DATA PRIVACY\nSET-UP",
     "body": ["Appoint a Data Protection Officer and register with the NPC when required.",
              "Conduct a Privacy Impact Assessment before go-live.",
              "Set data retention and secure disposal rules.",
              "Encrypt data in transit and at rest; give each role only the access it needs."],
     "out": "DPO appointment; Privacy Impact Assessment; NPC registration; documented security measures."},
    {"name": "BUILD &\nCONFIGURE",
     "body": ["Create individual accounts; no shared logins.",
              "Require strong passwords and multi-factor authentication where available.",
              "Configure the leave and request approval workflows.",
              "Enable an audit trail for every view, edit and approval."],
     "out": "Configured portal; workflow map; enabled audit logs; tested backup and restore."},
    {"name": "PILOT\n& TRAIN",
     "body": ["Test with one department for a full payroll cycle.",
              "Fix data errors before mass rollout.",
              "Train all users and issue a one-page how-to guide.",
              "Keep a manual fallback during the transition."],
     "out": "Pilot findings and fixes; training attendance records; published user guide."},
    {"name": "GO LIVE\n& MAINTAIN",
     "body": ["Publish payslips every cutoff and keep records for at least three years.",
              "Back up regularly and test restoration.",
              "Review user access quarterly; deactivate separated employees immediately.",
              "Keep a breach response plan; the NPC and affected persons are notified within 72 hours."],
     "out": "Live portal; quarterly access review log; backup schedule; breach response plan and incident register."},
  ],
  "note": "REMINDER: Personal data may be collected only for a declared purpose and kept no longer than necessary. Deactivate accounts on the separation date, not weeks later.",
 },
 {
  "file": "07-birthday-wall",
  "title": "BIRTHDAY WALL",
  "basis": "LEGAL BASIS: RA 10173 Data Privacy Act (consent, transparency, proportionality; a birth date is personal information) | RA 11313 Safe Spaces Act (respectful conduct in the workplace) | Company recognition and engagement policy",
  "what": "A simple recognition board that greets employees on their birthday and supports engagement at almost no cost. Because a birth date is personal information, it runs on voluntary opt-in consent and displays only the minimum, never the birth year or any contact detail. Participation and any contribution must always stay optional.",
  "phases": [
    {"name": "SET THE\nRULE",
     "body": ["Decide exactly what is displayed: name, department, and the day and month only.",
              "Never display the birth year, age, address or contact details.",
              "Define where it appears: portal, bulletin board or both.",
              "Approve the policy in writing."],
     "out": "Approved birthday wall policy stating the data displayed, the audience and the opt-out process."},
    {"name": "SECURE\nCONSENT",
     "body": ["Ask each employee to opt in; silence is not consent.",
              "Make clear that consent is voluntary and may be withdrawn anytime.",
              "Include the opt-in form in the onboarding pack for new hires.",
              "Keep a record of who opted in and who declined."],
     "out": "Signed or electronic opt-in records; maintained opt-out list; consent included in onboarding."},
    {"name": "BUILD\nTHE LIST",
     "body": ["Pull only opted-in records from the 201 file or HRIS.",
              "Sort by month and day.",
              "Restrict edit access to the HR administrator.",
              "Verify entries against official records to avoid wrong dates."],
     "out": "Verified monthly birthday list, for internal use only, with restricted access."},
    {"name": "PUBLISH\n& GREET",
     "body": ["Post at the start of the month or on the day itself.",
              "Keep the audience internal; no public social media posting without separate consent.",
              "Hold an optional monthly celebration.",
              "Keep greetings respectful and inclusive."],
     "out": "Published birthday post or announcement; monthly celebration record; greeting log."},
    {"name": "UPDATE\n& RESPECT",
     "body": ["Remove opt-outs and separated employees immediately.",
              "Review the list every month before posting.",
              "Never require attendance, gifts or contributions.",
              "Handle sensitive situations such as bereavement or illness with discretion."],
     "out": "Updated list; documented opt-out actions; monthly review confirmation."},
  ],
  "note": "REMINDER: A birthday wall is voluntary recognition, not a data collection exercise. Display the minimum, honor withdrawals at once, and never make celebration a condition of belonging.",
 },
 {
  "file": "08-performance-evaluation",
  "title": "PERFORMANCE EVALUATION",
  "basis": "LEGAL BASIS: Labor Code Art. 296 [281] Probationary Standards | Art. 297 [282] Just Causes | DOLE Department Order No. 147-15 | RA 10911 Anti-Age Discrimination | RA 9710 Magna Carta of Women | RA 7277 Magna Carta for Persons with Disability | RA 11313 Safe Spaces Act",
  "what": "A regular, evidence-based review of results and behavior against standards communicated in advance. It drives pay, promotion and training decisions, and when performance falls short it becomes the record that supports coaching, a PIP or, ultimately, a valid separation. Ratings must rest on documented performance, never on personal characteristics.",
  "phases": [
    {"name": "SET THE\nSTANDARDS",
     "body": ["Define KPIs and competencies per position, measurable and weighted.",
              "Issue them in writing at hiring and at the start of every cycle.",
              "For probationary staff, give the regularization standards at the time of engagement.",
              "Have the employee sign to acknowledge receipt."],
     "out": "Signed KPI and standards form per employee; approved rating scale and evaluation calendar."},
    {"name": "MONITOR\n& COACH",
     "body": ["Give feedback continuously, not once a year.",
              "Hold a documented mid-cycle review.",
              "Record incidents and achievements as they occur.",
              "There should be no surprises at the final rating."],
     "out": "Mid-cycle review form; dated coaching notes; incident and commendation records."},
    {"name": "RATE ON\nEVIDENCE",
     "body": ["The supervisor rates against documented evidence.",
              "Add self-assessment and peer or customer input where useful.",
              "Use one scale for everyone in the same job family.",
              "Write the justification behind every score."],
     "out": "Accomplished evaluation form with evidence cited; self-assessment; computed weighted rating."},
    {"name": "CALIBRATE\n& APPROVE",
     "body": ["Department heads calibrate ratings for consistency across teams.",
              "HR checks for bias: age, sex, pregnancy, disability, health status, union activity.",
              "Correct any rating the records do not support.",
              "Management approves the final distribution."],
     "out": "Calibration minutes; bias review checklist; approved final ratings and distribution."},
    {"name": "DISCUSS\n& ACT",
     "body": ["Discuss face to face; the employee signs and may write comments or appeal.",
              "Link the result to an increase, promotion, training or a PIP.",
              "Decide regularization before the six-month probationary period ends.",
              "File everything in the 201 file."],
     "out": "Signed appraisal with employee comments; development plan; regularization, reward or PIP decision."},
  ],
  "note": "REMINDER: A probationary employee not informed of the regularization standards at engagement becomes regular by operation of law, and one kept beyond six months becomes regular regardless of the rating.",
 },
]
